[project]
name = 'pay-per-use-api'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.pay-per-use-api]
path = 'contracts/pay-per-use-api.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
check-unchecked-data = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
